{
	"valid 1,2,4-byte read bpf_inet_lookup remote_ip4",
	.insns = {
		/* 4-byte read */
		BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip4)),
		/* 2-byte read */
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip4)),
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip4) + 2),
		/* 1-byte read */
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip4)),
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip4) + 3),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte read bpf_inet_lookup remote_ip4",
	.insns = {
		/* 8-byte read */
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip4)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte write bpf_inet_lookup remote_ip4",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x7f000001U),
		/* 4-byte write */
		BPF_STX_MEM(BPF_DW, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_ip4)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 4-byte write bpf_inet_lookup remote_ip4",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x7f000001U),
		/* 4-byte write */
		BPF_STX_MEM(BPF_W, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_ip4)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 2-byte write bpf_inet_lookup remote_ip4",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x7f000001U),
		/* 2-byte write */
		BPF_STX_MEM(BPF_H, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_ip4)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 1-byte write bpf_inet_lookup remote_ip4",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x7f000001U),
		/* 1-byte write */
		BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_ip4)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"valid 1,2,4-byte read bpf_inet_lookup local_ip4",
	.insns = {
		/* 4-byte read */
		BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip4)),
		/* 2-byte read */
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip4)),
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip4) + 2),
		/* 1-byte read */
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip4)),
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip4) + 3),
		BPF_MOV64_IMM(BPF_REG_0, 0),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte read bpf_inet_lookup local_ip4",
	.insns = {
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip4)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"valid 4-byte write bpf_inet_lookup local_ip4",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x7f000001U),
		BPF_STX_MEM(BPF_W, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_ip4)),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte write bpf_inet_lookup local_ip4",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x7f000001U),
		BPF_STX_MEM(BPF_DW, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_ip4)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 2-byte write bpf_inet_lookup local_ip4",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x7f000001U),
		BPF_STX_MEM(BPF_H, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_ip4)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 1-byte write bpf_inet_lookup local_ip4",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x7f000001U),
		BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_ip4)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"valid 1,2,4-byte read bpf_inet_lookup remote_ip6",
	.insns = {
		/* 4-byte read */
		BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip6[0])),
		BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip6[3])),
		/* 2-byte read */
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip6[0])),
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup,
				     remote_ip6[3]) + 2),
		/* 1-byte read */
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip6[0])),
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup,
				     remote_ip6[3]) + 3),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte read bpf_inet_lookup remote_ip6",
	.insns = {
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte write bpf_inet_lookup remote_ip6",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x00000001U),
		BPF_STX_MEM(BPF_DW, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 4-byte write bpf_inet_lookup remote_ip6",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x00000001U),
		BPF_STX_MEM(BPF_W, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 2-byte write bpf_inet_lookup remote_ip6",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x00000001U),
		BPF_STX_MEM(BPF_H, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 1-byte write bpf_inet_lookup remote_ip6",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x00000001U),
		BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"valid 1,2,4-byte read bpf_inet_lookup local_ip6",
	.insns = {
		/* 4-byte read */
		BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip6[0])),
		BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip6[3])),
		/* 2-byte read */
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip6[0])),
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip6[3]) + 2),
		/* 1-byte read */
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip6[0])),
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip6[3]) + 3),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte read bpf_inet_lookup local_ip6",
	.insns = {
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte write bpf_inet_lookup local_ip6",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x00000001U),
		BPF_STX_MEM(BPF_DW, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"valid 4-byte write bpf_inet_lookup local_ip6",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x00000001U),
		BPF_STX_MEM(BPF_W, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 2-byte write bpf_inet_lookup local_ip6",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x00000001U),
		BPF_STX_MEM(BPF_H, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 1-byte write bpf_inet_lookup local_ip6",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 0x00000001U),
		BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_ip6[0])),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"valid 4-byte read bpf_inet_lookup remote_port",
	.insns = {
		BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_port)),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte read bpf_inet_lookup remote_port",
	.insns = {
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 2-byte read bpf_inet_lookup remote_port",
	.insns = {
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 1-byte read bpf_inet_lookup remote_port",
	.insns = {
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, remote_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte write bpf_inet_lookup remote_port",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 1234),
		BPF_STX_MEM(BPF_DW, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 4-byte write bpf_inet_lookup remote_port",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 1234),
		BPF_STX_MEM(BPF_W, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 2-byte write bpf_inet_lookup remote_port",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 1234),
		BPF_STX_MEM(BPF_H, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 1-byte write bpf_inet_lookup remote_port",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 1234),
		BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, remote_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"valid 4-byte read bpf_inet_lookup local_port",
	.insns = {
		BPF_LDX_MEM(BPF_W, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_port)),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte read bpf_inet_lookup local_port",
	.insns = {
		BPF_LDX_MEM(BPF_DW, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 2-byte read bpf_inet_lookup local_port",
	.insns = {
		BPF_LDX_MEM(BPF_H, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 1-byte read bpf_inet_lookup local_port",
	.insns = {
		BPF_LDX_MEM(BPF_B, BPF_REG_0, BPF_REG_1,
			    offsetof(struct bpf_inet_lookup, local_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"valid 4-byte write bpf_inet_lookup local_port",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 1234),
		BPF_STX_MEM(BPF_W, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_port)),
		BPF_EXIT_INSN(),
	},
	.result = ACCEPT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 8-byte write bpf_inet_lookup local_port",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 1234),
		BPF_STX_MEM(BPF_DW, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 2-byte write bpf_inet_lookup local_port",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 1234),
		BPF_STX_MEM(BPF_H, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
{
	"invalid 1-byte write bpf_inet_lookup local_port",
	.insns = {
		BPF_MOV64_IMM(BPF_REG_0, 1234),
		BPF_STX_MEM(BPF_B, BPF_REG_1, BPF_REG_0,
			    offsetof(struct bpf_inet_lookup, local_port)),
		BPF_EXIT_INSN(),
	},
	.errstr = "invalid bpf_context access",
	.result = REJECT,
	.prog_type = BPF_PROG_TYPE_INET_LOOKUP,
},
